@ECHO OFF

pushd %~dp0

SET SPHINXBUILD=sphinx-build
SET SOURCEDIR=source
SET BUILDDIR=build
SET SPHINXPROJ=PookieCare

IF "%1"=="" (
	SET TARGET=help
) ELSE (
	SET TARGET=%1
)

%SPHINXBUILD% -M %TARGET% %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %SPHINXBUILD%
IF ERRORLEVEL 1 EXIT /B 1
popd
