# Generated by Django 5.2.7 on 2025-11-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='Or provide image URL (e.g., from CDN or external API)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Upload product image. Images will be stored in media/products/images/', null=True, upload_to='products/images/'),
        ),
    ]
