# Generated by Django 5.2.7 on 2025-12-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional order note or special instructions'),
        ),
    ]
